import Head from 'next/head'
import { Space_Grotesk, Poppins } from '@next/font/google'

const spaceGrotesk = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--ff-space-grotesk",
})

const poppins = Poppins({
  weight: ['400', '500'],
  subsets: ["latin"],
  variable: "--ff-poppins",
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          :root {
            --merriweather: ${merriweather.style.fontFamily};
            --work-sans: ${workSans.style.fontFamily};
            --roboto-mono: ${robotoMono.style.fontFamily};
          }
        `}</style>
      </Head>
      <main className="">
      </main>
    </>
  )
}
